services:
  omega.api:
    image: omega.api
    build:
      context: .
      dockerfile: Omega.Api/Dockerfile
    ports:
      - "5001:8081"
      - "5000:8080"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4317"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: Keycloak
    environment:
      - KC_HEALTH_ENABLED=true
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    command: start-dev
    volumes:
      - ./.containers/identity:/opt/keycloak/data
    ports:
      - "18080:8080"
    
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: Jaeger
    ports:
      - "4317:4317"
      - "4318:4318"
      - "16686:16686"